// ---------------------------------------------
// C implementation for cordic algorithm
// This program does not use floats nor doubles
// ---------------------------------------------
//          Made by Kacper Górski
// ---------------------------------------------

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define K 0x26DD3B6A

#define SCALE 1073741824.0

#define ACAN_SIZE 32

int ACAN_TABLE[]  = {
	0x3243f6a8, 0x1dac6705, 0x0fadbafc, 0x07f56ea6, 0x03feab76,
	0x01ffd55b, 0x00fffaaa, 0x007fff55, 0x003fffea, 0x001ffffd,
	0x000fffff, 0x0007ffff, 0x0003ffff, 0x0001ffff, 0x0000ffff, 0x00007fff, 0x00003fff,
	0x00001fff, 0x00000fff, 0x000007ff, 0x000003ff, 0x000001ff, 0x000000ff, 0x0000007f, 0x0000003f, 0x0000001f,
	0x0000000f, 0x00000008, 0x00000004, 0x00000002, 0x00000001, 0x00000000,
};
// ------------------------------------------
//            CORDIC ALGORITHM
// ------------------------------------------
int* CORDIC(int theta_deg) {
    // Determine scaling factor (Generated by Python code)
    int x_point = K;
    int y_point = 0;
    int z = theta_deg;
    int i;

    // Algorithm
    for(i = 0; i < ACAN_SIZE; ++i) {
        int dx = y_point >> i;
        int dy = x_point >> i;
        int dz = ACAN_TABLE[i];

        if (z < 0) {
            x_point += dx;
            y_point -= dy;
            z += dz;
        }
        else {
            x_point -= dx;
            y_point += dy;
            z -= dz;
        }
    }

    int* result = (int*)malloc(2 * sizeof(int));
    if (result == NULL) {
        return NULL;
    }

    result[0] = x_point;
    result[1] = y_point;
    return result;
}


// ------------------------------------------
//                    main
// ------------------------------------------
int main() {
    // Determine variables
    double angle_deg = 3.14 / 4.0;
    double scaled_angle = angle_deg * SCALE;

    int* cordic_result = CORDIC(scaled_angle);

    if (cordic_result == NULL) {
        return -1;
    }

    // Sine and cosine computed through CORDIC
    double sine = cordic_result[1] / SCALE;
    double cosine = cordic_result[0] / SCALE;

    // Print result
    printf("Sine: %d", sine, '\n');
    printf(" Cosine: %d", cosine);

    free(cordic_result);
    return 0;
}
// ------------------------------------------
