// ---------------------------------------------
// C implementation for cordic algorithm
// This program does not use floats nor doubles
// ---------------------------------------------
//          Made by Kacper Górski
// ---------------------------------------------

#include <stdio.h>
#include <stdlib.h>
#include <corecrt_math_defines.h>

#define K 0x26DD3B6A

#define SCALE 1073741824.0

#define ACAN_SIZE 32

int ACAN_TABLE[] = {0x3243f6a8, 0x1dac6705, 0xfadbafc, 0x7f56ea6,
    0x3feab76, 0x1ffd55b, 0xfffaaa, 0x7fff55, 0x3fffea, 0x1ffffd,
    0xfffff, 0x7ffff, 0x3ffff, 0x1ffff, 0xffff, 0x7fff, 0x3fff,
    0x1fff, 0xfff, 0x7ff, 0x3ff, 0x1ff, 0xff, 0x7f, 0x3f, 0x1f,
    0xf, 0x8, 0x4, 0x2, 0x1, 0x0};
// ------------------------------------------
//            CORDIC ALGORITHM
// ------------------------------------------
int* CORDIC(int theta_deg) {
    // Determine scaling factor (Generated by Python code)
    int x_point = K;
    int y_point = 0;
    int z = theta_deg;

    // Algorithm
    for(int i = 0; i < ACAN_SIZE; ++i) {
        int dx = y_point >> i;
        int dy = x_point >> i;
        int dz = ACAN_TABLE[i];

        if (z < 0) {
            x_point += dx;
            y_point -= dy;
            z += dz;
        }
        else {
            x_point -= dx;
            y_point += dy;
            z -= dz;
        }

    int* result = (int*)malloc(2 * sizeof(int));
    // Memory allocation error
    if (result == NULL) {
        return NULL;
    }
    result[0] = x_point;
    result[1] = y_point;

    return result;
    }
}

// ------------------------------------------
//                    main
// ------------------------------------------
int main() {
    // Determine variables
    double angle_deg = M_PI / 4;
    double fixed_angle = angle_deg * SCALE;

    int* cordic_result = CORDIC(fixed_angle);

    if (cordic_result == NULL) {
        return -1;
    }

    // Sine and cosine computed through CORDIC
    double sine = cordic_result[1] / SCALE;
    double cosine = cordic_result[0] / SCALE;

    // Print result
    printf("Sine: %d", sine, '\n');
    printf(" Cosine: %d", cosine);
	
    free(cordic_result);
    return 0;
}
// ------------------------------------------
